-- Workout Plan starter seed (copy of record — already applied live).
-- 33 exercises (demo photos from the public-domain free-exercise-db) and the
-- 7 workouts in the library. The profile row (personal stats) and the admin
-- password are set live, not committed -- see the commented example at the
-- bottom.

insert into workout_exercises (id,name,muscle,equipment,setting,image_url,instructions,sort_order) values
('db-floor-press','Dumbbell Floor Press','triceps','dumbbell','home','https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Floor_Press/0.jpg','Lay on the floor holding dumbbells in your hands. Your knees can be bent. Begin with the weights fully extended above you. Lower the weights until your upper arm comes in contact with the floor. You can tuck your elbows to emphasize triceps size and strength, or to focus on your chest angle your arms to the side. Pause at the bottom, and then bring the weight together at the top by extending through the elbows.',1),
('db-shoulder-press','Dumbbell Shoulder Press','shoulders','dumbbell','home','https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Dumbbell_Press/0.jpg','Standing with your feet shoulder width apart, take a dumbbell in each hand. Raise the dumbbells to head height, the elbows out and about 90 degrees. This will be your starting position. Maintaining strict technique with no leg drive or leaning back, extend through the elbow to raise the weights together directly above your head. Pause, and slowly return the weight to the starting position.',2),
('pushups','Push-Ups','chest','body only','home','https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pushups/0.jpg','Lie on the floor face down and place your hands about 36 inches apart while holding your torso up at arms length. Next, lower yourself downward until your chest almost touches the floor as you inhale. Now breathe out and press your upper body back up to the starting position while squeezing your chest. After a brief pause at the top contracted position, you can begin to lower yourself downward again for as many repetitions as needed.',3),
('side-lateral-raise','Side Lateral Raise','shoulders','dumbbell','home','https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Side_Lateral_Raise/0.jpg','Pick a couple of dumbbells and stand with a straight torso and the dumbbells by your side at arms length with the palms of the hand facing you. This will be your starting position. While maintaining the torso in a stationary position (no swinging), lift the dumbbells to your side with a slight bend on the elbow and the hands slightly tilted forward as if pouring water in a glass. Continue to go up until you arms are parallel to the floor. Exhale as you execute this movement and pause for a second at the top. Lower the dumbbells back down slowly to the starting position as you inhale. Repeat for the recommended amount of repetitions.',4),
('oh-triceps-ext','Overhead Triceps Extension','triceps','dumbbell','home','https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Dumbbell_Triceps_Extension/0.jpg','To begin, stand up with a dumbbell held by both hands. Your feet should be about shoulder width apart from each other. Slowly use both hands to grab the dumbbell and lift it over your head until both arms are fully extended. The resistance should be resting in the palms of your hands with your thumbs around it. The palm of the hands should be facing up towards the ceiling. This will be your starting position. Keeping your upper arms close to your head with elbows in and perpendicular to the floor, lower the resistance in a semicircular motion behind your head until your forearms touch your biceps. Tip: The upper arms should remain stationary and only the forearms should move. Breathe in as you perform this step. Go back to the starting position by using the triceps to raise the dumbbell. Breathe out as you perform this step. Repeat for the recommended amount of repetitions.',5),
('ab-wheel','Ab Wheel Roll-out','abdominals','other','both','https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Ab_Roller/0.jpg','Hold the Ab Roller with both hands and kneel on the floor. Now place the ab roller on the floor in front of you so that you are on all your hands and knees (as in a kneeling push up position). This will be your starting position. Slowly roll the ab roller straight forward, stretching your body into a straight position. Tip: Go down as far as you can without touching the floor with your body. Breathe in during this portion of the movement. After a pause at the stretched position, start pulling yourself back to the starting position as you breathe out. Tip: Go slowly and keep your abs tight at all times.',6),
('leg-press','Leg Press','quadriceps','machine','gym','https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Press/0.jpg','Using a leg press machine, sit down on the machine and place your legs on the platform directly in front of you at a medium (shoulder width) foot stance. (Note: For the purposes of this discussion we will use the medium stance described above which targets overall development; however you can choose any of the three stances described in the foot positioning section). Lower the safety bars holding the weighted platform in place and press the platform all the way up until your legs are fully extended in front of you. Tip: Make sure that you do not lock your knees. Your torso and the legs should make a perfect 90-degree angle. This will be your starting position. As you inhale, slowly lower the platform until your upper and lower legs make a 90-degree angle. Pushing mainly with the heels of your feet and using the quadriceps go back to the starting position as you exhale. Repeat for the recommended amount of repetitions and ensure to lock the safety pins properly once you are done. You do not want that platform falling on you fully loaded.',7),
('machine-bench','Chest Press (Machine)','chest','machine','gym','https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Machine_Bench_Press/0.jpg','Sit down on the Chest Press Machine and select the weight. Step on the lever provided by the machine since it will help you to bring the handles forward so that you can grab the handles and fully extend the arms. Grab the handles with a palms-down grip and lift your elbows so that your upper arms are parallel to the floor to the sides of your torso. Tip: Your forearms will be pointing forward since you are grabbing the handles. Once you bring the handles forward and extend the arms you will be at the starting position. Now bring the handles back towards you as you breathe in. Push the handles away from you as you flex your pecs and you breathe out. Hold the contraction for a second before going back to the starting position. Repeat for the recommended amount of reps. When finished step on the lever again and slowly get the handles back to their original place.',8),
('lat-pulldown','Lat Pulldown','lats','cable','gym','https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wide-Grip_Lat_Pulldown/0.jpg','Sit down on a pull-down machine with a wide bar attached to the top pulley. Make sure that you adjust the knee pad of the machine to fit your height. These pads will prevent your body from being raised by the resistance attached to the bar. Grab the bar with the palms facing forward using the prescribed grip. Note on grips: For a wide grip, your hands need to be spaced out at a distance wider than shoulder width. For a medium grip, your hands need to be spaced out at a distance equal to your shoulder width and for a close grip at a distance smaller than your shoulder width. As you have both arms extended in front of you holding the bar at the chosen grip width, bring your torso back around 30 degrees or so while creating a curvature on your lower back and sticking your chest out. This is your starting position. As you breathe out, bring the bar down until it touches your upper chest by drawing the shoulders and the upper arms down and back. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. The upper torso should remain stationary and only the arms should move. The forearms should do no other work except for holding the bar; therefore do not try to pull down the bar using the forearms. After a second at the contracted position squeezing your shoulder blades together, slowly raise the bar back to the starting position when your arms are fully extended and the lats are fully stretched. Inhale during this portion of the movement. Repeat this motion for the prescribed amount of repetitions.',9),
('seated-row','Seated Cable Row','middle back','cable','gym','https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Cable_Rows/0.jpg','For this exercise you will need access to a low pulley row machine with a V-bar. Note: The V-bar will enable you to have a neutral grip where the palms of your hands face each other. To get into the starting position, first sit down on the machine and place your feet on the front platform or crossbar provided making sure that your knees are slightly bent and not locked. Lean over as you keep the natural alignment of your back and grab the V-bar handles. With your arms extended pull back until your torso is at a 90-degree angle from your legs. Your back should be slightly arched and your chest should be sticking out. You should be feeling a nice stretch on your lats as you hold the bar in front of you. This is the starting position of the exercise. Keeping the torso stationary, pull the handles back towards your torso while keeping the arms close to it until you touch the abdominals. Breathe out as you perform that movement. At that point you should be squeezing your back muscles hard. Hold that contraction for a second and slowly go back to the original position while breathing in. Repeat for the recommended amount of repetitions.',10),
('romanian-deadlift','Romanian Deadlift','hamstrings','barbell','gym','https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Romanian_Deadlift/0.jpg','Put a barbell in front of you on the ground and grab it using a pronated (palms facing down) grip that a little wider than shoulder width. Tip: Depending on the weight used, you may need wrist wraps to perform the exercise and also a raised platform in order to allow for better range of motion. Bend the knees slightly and keep the shins vertical, hips back and back straight. This will be your starting position. Keeping your back and arms completely straight at all times, use your hips to lift the bar as you exhale. Tip: The movement should not be fast but steady and under control. Once you are standing completely straight up, lower the bar by pushing the hips back, only slightly bending the knees, unlike when squatting. Tip: Take a deep breath at the start of the movement and keep your chest up. Hold your breath as you lower and exhale as you complete the movement. Repeat for the recommended amount of repetitions.',11),
('db-rdl','Dumbbell Romanian Deadlift','hamstrings','dumbbell','home','https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Stiff-Legged_Dumbbell_Deadlift/0.jpg','Grasp a couple of dumbbells holding them by your side at arm''s length. Stand with your torso straight and your legs spaced using a shoulder width or narrower stance. The knees should be slightly bent. This is your starting position. Keeping the knees stationary, lower the dumbbells to over the top of your feet by bending at the waist while keeping your back straight. Keep moving forward as if you were going to pick something from the floor until you feel a stretch on the hamstrings. Exhale as you perform this movement Start bringing your torso up straight again by extending your hips and waist until you are back at the starting position. Inhale as you perform this movement. Repeat for the recommended amount of repetitions.',12),
('calf-raise','Standing Calf Raise','calves','machine','both','https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Calf_Raises/0.jpg','Adjust the padded lever of the calf raise machine to fit your height. Place your shoulders under the pads provided and position your toes facing forward (or using any of the two other positions described at the beginning of the chapter). The balls of your feet should be secured on top of the calf block with the heels extending off it. Push the lever up by extending your hips and knees until your torso is standing erect. The knees should be kept with a slight bend; never locked. Toes should be facing forward, outwards or inwards as described at the beginning of the chapter. This will be your starting position. Raise your heels as you breathe out by extending your ankles as high as possible and flexing your calf. Ensure that the knee is kept stationary at all times. There should be no bending at any time. Hold the contracted position by a second before you start to go back down. Go back slowly to the starting position as you breathe in by lowering your heels as you bend the ankles until calves are stretched. Repeat for the recommended amount of repetitions.',13),
('hanging-leg-raise','Hanging Leg Raise','abdominals','body only','gym','https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hanging_Leg_Raise/0.jpg','Hang from a chin-up bar with both arms extended at arms length in top of you using either a wide grip or a medium grip. The legs should be straight down with the pelvis rolled slightly backwards. This will be your starting position. Raise your legs until the torso makes a 90-degree angle with the legs. Exhale as you perform this movement and hold the contraction for a second or so. Go back slowly to the starting position as you breathe in. Repeat for the recommended amount of repetitions.',14),
('split-squat','Dumbbell Split Squat','quadriceps','dumbbell','home','https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Split_Squat_with_Dumbbells/0.jpg','Position yourself into a staggered stance with the rear foot elevated and front foot forward. Hold a dumbbell in each hand, letting them hang at the sides. This will be your starting position. Begin by descending, flexing your knee and hip to lower your body down. Maintain good posture througout the movement. Keep the front knee in line with the foot as you perform the exercise. At the bottom of the movement, drive through the heel to extend the knee and hip to return to the starting position.',15),
('chin-up','Chin-Up','lats','body only','home','https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Chin-Up/0.jpg','Grab the pull-up bar with the palms facing your torso and a grip closer than the shoulder width. As you have both arms extended in front of you holding the bar at the chosen grip width, keep your torso as straight as possible while creating a curvature on your lower back and sticking your chest out. This is your starting position. Tip: Keeping the torso as straight as possible maximizes biceps stimulation while minimizing back involvement. As you breathe out, pull your torso up until your head is around the level of the pull-up bar. Concentrate on using the biceps muscles in order to perform the movement. Keep the elbows close to your body. Tip: The upper torso should remain stationary as it moves through space and only the arms should move. The forearms should do no other work other than hold the bar. After a second of squeezing the biceps in the contracted position, slowly lower your torso back to the starting position; when your arms are fully extended. Breathe in as you perform this portion of the movement. Repeat this motion for the prescribed amount of repetitions.',16),
('db-row','One-Arm Dumbbell Row','middle back','dumbbell','home','https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Dumbbell_Row/0.jpg','Choose a flat bench and place a dumbbell on each side of it. Place the right leg on top of the end of the bench, bend your torso forward from the waist until your upper body is parallel to the floor, and place your right hand on the other end of the bench for support. Use the left hand to pick up the dumbbell on the floor and hold the weight while keeping your lower back straight. The palm of the hand should be facing your torso. This will be your starting position. Pull the resistance straight up to the side of your chest, keeping your upper arm close to your side and keeping the torso stationary. Breathe out as you perform this step. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. Also, make sure that the force is performed with the back muscles and not the arms. Finally, the upper torso should remain stationary and only the arms should move. The forearms should do no other work except for holding the dumbbell; therefore do not try to pull the dumbbell up using the forearms. Lower the resistance straight down to the starting position. Breathe in as you perform this step. Repeat the movement for the specified amount of repetitions. Switch sides and repeat again with the other arm.',17),
('glute-bridge','Glute Bridge','glutes','body only','both','https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Butt_Lift_Bridge/0.jpg','Lie flat on the floor on your back with the hands by your side and your knees bent. Your feet should be placed around shoulder width. This will be your starting position. Pushing mainly with your heels, lift your hips off the floor while keeping your back straight. Breathe out as you perform this part of the motion and hold at the top for a second. Slowly go back to the starting position as you breathe in.',18),
('db-curl','Dumbbell Biceps Curl','biceps','dumbbell','home','https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Bicep_Curl/0.jpg','Stand up straight with a dumbbell in each hand at arm''s length. Keep your elbows close to your torso and rotate the palms of your hands until they are facing forward. This will be your starting position. Now, keeping the upper arms stationary, exhale and curl the weights while contracting your biceps. Continue to raise the weights until your biceps are fully contracted and the dumbbells are at shoulder level. Hold the contracted position for a brief pause as you squeeze your biceps. Then, inhale and slowly begin to lower the dumbbells back to the starting position. Repeat for the recommended amount of repetitions.',19),
('rear-delt-fly','Rear Delt Fly','shoulders','dumbbell','home','https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lying_Rear_Delt_Raise/0.jpg','While holding a dumbbell in each hand, lay with your chest down on a flat bench. Position the palms of the hands in a neutral manner (palms facing your torso) as you keep the arms extended with the elbows slightly bent. This will be your starting position. Now raise the arms to the side until your elbows are at shoulder height and your arms are roughly parallel to the floor as you exhale. Tip: Maintain your arms perpendicular to the torso while keeping them extended throughout the movement. Also, keep the contraction at the top for a second. Slowly lower the dumbbells to the starting position as you inhale. Repeat for the recommended amount of repetitions and then switch to the other arm.',20),
('goblet-squat','Goblet Squat','quadriceps','kettlebells','home','https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Goblet_Squat/0.jpg','Stand holding a light kettlebell by the horns close to your chest. This will be your starting position. Squat down between your legs until your hamstrings are on your calves. Keep your chest and head up and your back straight. At the bottom position, pause and use your elbows to push your knees out. Return to the starting position, and repeat for 10-20 repetitions.',21),
('rear-lunge','Dumbbell Reverse Lunge','quadriceps','dumbbell','home','https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Rear_Lunge/0.jpg','Stand with your torso upright holding two dumbbells in your hands by your sides. This will be your starting position. Step backward with your right leg around two feet or so from the left foot and lower your upper body down, while keeping the torso upright and maintaining balance. Inhale as you go down. Tip: As in the other exercises, do not allow your knee to go forward beyond your toes as you come down, as this will put undue stress on the knee joint. Make sure that you keep your front shin perpendicular to the ground. Keep the torso upright during the lunge; flexible hip flexors are important. A long lunge emphasizes the Gluteus Maximus; a short lunge emphasizes Quadriceps. Push up and go back to the starting position as you exhale. Tip: Use the ball of your feet to push in order to accentuate the quadriceps. To focus on the glutes, press with your heels. Now repeat with the opposite leg.',22),
('plank','Plank','abdominals','body only','home','https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Plank/0.jpg','Get into a prone position on the floor, supporting your weight on your toes and your forearms. Your arms are bent and directly below the shoulder. Keep your body straight at all times, and hold this position as long as possible. To increase difficulty, an arm or leg can be raised.',23),
('leg-swings','Leg Swings','hamstrings','body only','both','https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Front_Leg_Raises/0.jpg','Stand next to a chair or other support, holding on with one hand. Swing your leg forward, keeping the leg straight. Continue with a downward swing, bringing the leg as far back as your flexibility allows. Repeat 5-10 times, and then switch legs.',24),
('hip-circles','Standing Hip Circles','abductors','body only','both','https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Hip_Circles/0.jpg','Begin standing on one leg, holding to a vertical support. Raise the unsupported knee to 90 degrees. This will be your starting position. Open the hip as far as possible, attempting to make a big circle with your knee. Perform this movement slowly for a number of repetitions, and repeat on the other side.',25),
('inchworm','Inchworm','hamstrings','body only','both','https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Inchworm/0.jpg','Stand with your feet close together. Keeping your legs straight, stretch down and put your hands on the floor directly in front of you. This will be your starting position. Begin by walking your hands forward slowly, alternating your left and your right. As you do so, bend only at the hip, keeping your legs straight. Keep going until your body is parallel to the ground in a pushup position. Now, keep your hands in place and slowly take short steps with your feet, moving only a few inches at a time. Continue walking until your feet are by your hands, keeping your legs straight as you do so.',26),
('worlds-greatest','World''s Greatest Stretch','hamstrings','body only','both','https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Worlds_Greatest_Stretch/0.jpg','This is a three-part stretch. Begin by lunging forward, with your front foot flat on the ground and on the toes of your back foot. With your knees bent, squat down until your knee is almost touching the ground. Keep your torso erect, and hold this position for 10-20 seconds. Now, place the arm on the same side as your front leg on the ground, with the elbow next to the foot. Your other hand should be placed on the ground, parallel to your lead leg, to help support you during this portion of the stretch. After 10-20 seconds, place your hands on either side of your front foot. Raise the toes of the front foot off of the ground, and straighten your leg. You may need to reposition your rear leg to do so. Hold for 10-20 seconds, and then repeat the entire sequence for the other side.',27),
('cat-stretch','Cat Stretch','lower back','body only','both','https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cat_Stretch/0.jpg','Position yourself on the floor on your hands and knees. Pull your belly in and round your spine, lower back, shoulders, and neck, letting your head drop. Hold for 15 seconds.',28),
('childs-pose','Child''s Pose','lower back','body only','both','https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Childs_Pose/0.jpg','Get on your hands and knees, walk your hands in front of you. Lower your buttocks down to sit on your heels. Let your arms drag along the floor as you sit back to stretch your entire spine. Once you settle onto your heels, bring your hands next to your feet and relax. Breathe into your back. Rest your forehead on the floor. Avoid this position if you have knee problems.',29),
('kneel-hip-flexor','Kneeling Hip Flexor Stretch','quadriceps','body only','both','https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kneeling_Hip_Flexor/0.jpg','Kneel on a mat and bring your right knee up so the bottom of your foot is on the floor and extend your left leg out behind you so the top of your foot is on the floor. Shift your weight forward until you feel a stretch in your hip. Hold for 15 seconds, then repeat for your other side.',30),
('knee-across-body','Knee Across The Body','glutes','body only','both','https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Knee_Across_The_Body/0.jpg','Lie down on the floor with your right leg straight. Bend your left leg and lower it across your body, holding the knee down toward the floor with your right hand. (The knee does not need to touch the floor if you are tight.) Place your left arm comfortably beside you and turn your head to the left. Imagine you have a weight tied to your tailbone — let your tailbone fall back toward the floor as your chest reaches in the opposite direction to stretch your lower back. Switch sides.',31),
('runners-stretch','Runner''s Stretch','hamstrings','body only','both','https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Runners_Stretch/0.jpg','It is easiest to get into this stretch if you start standing up, put one leg behind you, and slowly lower your torso down to the floor. Keep the front heel on the floor (if it lifts up, scoot your other leg further back). Place your hands on either side of your front leg. To get more out of this stretch, push your butt up toward the ceiling, and then gradually lower it back toward the floor. You will stretch the hip flexor of the back leg and the hamstring and buttocks of the front.',32),
('elbows-back','Elbows Back','chest','body only','both','https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Elbows_Back/0.jpg','Stand up straight. Place both hands on your lower back, fingers pointing downward and elbows out. Then gently pull your elbows back, aiming to touch them together.',33)
on conflict (id) do nothing;

insert into workout_routines (id,title,kind,subtitle,summary,est_minutes,sort_order) values
('push','Push Day','home','Chest · Shoulders · Triceps','Everything that pushes — chest, shoulders and triceps — with the dumbbells at home. Rest 60–90 seconds between sets and stop a rep or two short of failure on the compounds.',35,1),
('pull','Pull Day','home','Back · Biceps · Rear delts','Back, biceps and rear delts. Chin-ups first while you are fresh, then rows and curls. If a full chin-up is still out of reach, jump to the top and lower yourself as slowly as you can.',30,2),
('lower-core','Lower + Core','home','Legs · Glutes · Core','Legs, glutes and core. Depth beats load — get your hips below your knees on the squats before you reach for a heavier dumbbell.',35,3),
('full-body-home','Full Body (home)','home','Whole body · dumbbells only','The whole body in one session with nothing but dumbbells and a bar. This is the one for a day the gym or your padel partner falls through.',35,4),
('full-body-gym','Full Body (gym)','gym','Planet Fitness — go heavy','Machines and free weights at the gym — the one day a week to go genuinely heavy. Leg press first while your legs are fresh, core last.',45,5),
('run-5k','parkrun 5 km','run','Warm up, then chase the clock','Four minutes of dynamic warm-up, then run. Go out slower than feels right for the first kilometre and finish strong. Log the time on Progress afterwards.',40,6),
('mobility','Mobility & Stretch','mobility','Rest-day reset','Ten minutes of stretching on a rest day, or straight after a run while you are still warm. Hold each one for about 30 seconds and keep breathing — never bounce.',12,7)
on conflict (id) do nothing;

insert into workout_routine_exercises (routine_id,exercise_id,sort_order,target_sets,target_reps,note) values
('push','db-floor-press',1,3,'10',''),
('push','db-shoulder-press',2,3,'10',''),
('push','pushups',3,3,'12','Slow the tempo as it gets easy'),
('push','side-lateral-raise',4,3,'15','Light — form over weight'),
('push','oh-triceps-ext',5,3,'12',''),
('push','ab-wheel',6,3,'8-10','From knees'),
('full-body-gym','leg-press',1,4,'10',''),
('full-body-gym','machine-bench',2,3,'10',''),
('full-body-gym','lat-pulldown',3,3,'10',''),
('full-body-gym','seated-row',4,3,'10',''),
('full-body-gym','romanian-deadlift',5,3,'10','Feel the hamstring stretch'),
('full-body-gym','calf-raise',6,4,'15',''),
('full-body-gym','hanging-leg-raise',7,3,'12',''),
('full-body-home','split-squat',1,3,'10 each','Hold your dumbbells'),
('full-body-home','pushups',2,3,'12',''),
('full-body-home','chin-up',3,3,'AMRAP','Negatives if needed'),
('full-body-home','db-row',4,3,'10 each',''),
('full-body-home','glute-bridge',5,3,'15',''),
('full-body-home','ab-wheel',6,3,'8-10',''),
('pull','chin-up',1,3,'AMRAP','Slow negatives build strength'),
('pull','db-row',2,3,'10 each',''),
('pull','db-curl',3,3,'12',''),
('pull','rear-delt-fly',4,3,'15','Light'),
('pull','ab-wheel',5,3,'8-10',''),
('lower-core','goblet-squat',1,3,'12',''),
('lower-core','rear-lunge',2,3,'10 each',''),
('lower-core','db-rdl',3,3,'12',''),
('lower-core','glute-bridge',4,3,'15','Squeeze at the top'),
('lower-core','calf-raise',5,3,'20',''),
('lower-core','plank',6,3,'45s',''),
('run-5k','leg-swings',1,1,'10 each leg','Hold a pole or a wall'),
('run-5k','hip-circles',2,1,'8 each way',''),
('run-5k','inchworm',3,1,'5 walk-outs',''),
('run-5k','worlds-greatest',4,1,'4 each side','The one that actually matters before a run'),
('mobility','cat-stretch',1,1,'30 sec','Round and release slowly, in time with your breathing'),
('mobility','childs-pose',2,1,'45 sec','Breathe into your lower back'),
('mobility','kneel-hip-flexor',3,1,'30 sec each side','Squeeze the glute of the kneeling leg'),
('mobility','knee-across-body',4,1,'30 sec each side',''),
('mobility','runners-stretch',5,1,'30 sec each side','Front heel stays down'),
('mobility','elbows-back',6,1,'20 sec × 3','Undoes a day at a desk');

-- Personal profile + starting bodyweight are set live, e.g.:
--   insert into workout_profile (id,dob,height_cm,sex,goal,target_weight_kg,activity_factor)
--   values (1,'YYYY-MM-DD',170,'male','recomp',65,1.5) on conflict (id) do nothing;
-- And set the real admin password (never commit it) — stored hashed, so the
-- plaintext never lands in the database:
--   update workout_settings
--   set value = extensions.crypt('your-password', extensions.gen_salt('bf', 10))
--   where key = 'admin_password';

